<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use App\Models\Formacion;

class FormacionSeeder extends Seeder
{
    public function run()
    {
        $formaciones = [
            // Talleres
            [
                'nombre' => 'TALLER CONOCIENDO EL FUNCIONAMIENTO DE NUESTRO CUERPO',
                'tipo' => 'T',
                'descripcion' => 'Los niños y las niñas también saben de ciencia. El secreto está en las estrategias de enseñanza y aprendizaje.',
                'categoria' => 'Taller',
                'duracion' => 10,
                'disponible' => true,
                'disponible_hoy' => true,
            ],
            [
                'nombre' => 'TALLER APRENDIENDO SOBRE EL MUNDO ANIMAL',
                'tipo' => 'T',
                'descripcion' => 'Descripción del taller sobre el mundo animal.',
                'categoria' => 'Taller',
                'duracion' => 10,
                'disponible' => true,
                'disponible_hoy' => true,
            ],
            [
                'nombre' => 'INTERDISCIPLENARIEDAD EN LAS CIENCIAS NATURALES',
                'tipo' => 'T',
                'descripcion' => 'Taller sobre interdisciplinariedad en ciencias naturales.',
                'categoria' => 'Taller',
                'duracion' => 10,
                'disponible' => true,
                'disponible_hoy' => true,
            ],
            [
                'nombre' => 'ESTRATEGIAS DIDÁCTICAS PARA LA INNOVACIÓN EN LA ENSEÑANZA Y APRENDIZAJE DE LA BIOLOGÍA',
                'tipo' => 'T',
                'descripcion' => 'Estrategias innovadoras para la enseñanza de biología.',
                'categoria' => 'Taller',
                'duracion' => 10,
                'disponible' => true,
                'disponible_hoy' => true,
            ],
            [
                'nombre' => 'ESTRATEGIAS DIDÁCTICAS PARA LA INNOVACIÓN EN LA ENSEÑANZA Y EL APRENDIZAJE DEL USO Y EL MANEJO DE LOS INSTRUMENTOS DE LABORATORIO',
                'tipo' => 'T',
                'descripcion' => 'Taller sobre manejo de instrumentos de laboratorio.',
                'categoria' => 'Taller',
                'duracion' => 10,
                'disponible' => true,
                'disponible_hoy' => true,
            ],
            [
                'nombre' => 'MANEJO DE MATERIALES DEL KIT DE LABORATORIO DE BIOLOGÍA',
                'tipo' => 'T',
                'descripcion' => 'Taller práctico sobre materiales de laboratorio de biología.',
                'categoria' => 'Taller',
                'duracion' => 10,
                'disponible' => true,
                'disponible_hoy' => true,
            ],
            [
                'nombre' => 'El divertido mundo de las plantas',
                'tipo' => 'T',
                'descripcion' => 'Taller interactivo sobre el mundo vegetal.',
                'categoria' => 'Taller',
                'duracion' => 10,
                'disponible' => true,
                'disponible_hoy' => true,
            ],
            [
                'nombre' => 'ESTRATEGIAS DIDÁCTICAS PARA LA INNOVACIÓN EN LA ENSEÑANZA Y EL APRENDIZAJE DE LA FÍSICA',
                'tipo' => 'T',
                'descripcion' => 'Estrategias innovadoras para la enseñanza de física.',
                'categoria' => 'Taller',
                'duracion' => 10,
                'disponible' => true,
                'disponible_hoy' => true,
            ],
            [
                'nombre' => 'LA DIDÁCTICA DE LA FÍSICA DESDE EL ERROR DE LOS CONCEPTOS Y SUS APLICACIONES EN EL AULA',
                'tipo' => 'T',
                'descripcion' => 'Taller sobre didáctica de la física.',
                'categoria' => 'Taller',
                'duracion' => 10,
                'disponible' => true,
                'disponible_hoy' => true,
            ],
            [
                'nombre' => 'Descubriendo la cotidianidad a través del juego para la mejora de la calidad educativa',
                'tipo' => 'T',
                'descripcion' => 'Taller sobre aprendizaje a través del juego.',
                'categoria' => 'Taller',
                'duracion' => 10,
                'disponible' => true,
                'disponible_hoy' => true,
            ],
            [
                'nombre' => 'Física Recreativa',
                'tipo' => 'T',
                'descripcion' => 'Taller de física aplicada de forma recreativa.',
                'categoria' => 'Taller',
                'duracion' => 10,
                'disponible' => true,
                'disponible_hoy' => true,
            ],
            [
                'nombre' => 'Los juegos tradicionales aplicados a la física',
                'tipo' => 'T',
                'descripcion' => 'Taller sobre física a través de juegos tradicionales.',
                'categoria' => 'Taller',
                'duracion' => 10,
                'disponible' => true,
                'disponible_hoy' => true,
            ],
            [
                'nombre' => 'Diseño para la Elaboración de Materiales Educativos Alternativos para la Enseñanza de las Ciencias Integradas',
                'tipo' => 'T',
                'descripcion' => 'Taller sobre creación de materiales educativos.',
                'categoria' => 'Taller',
                'duracion' => 10,
                'disponible' => true,
                'disponible_hoy' => true,
            ],
            [
                'nombre' => 'MANEJO DE MATERIALES DEL KIT DE LABORATORIO DE FÍSICA (MECANICA I/PARTE I)',
                'tipo' => 'T',
                'descripcion' => 'Taller sobre manejo de materiales de laboratorio de física parte I.',
                'categoria' => 'Taller',
                'duracion' => 10,
                'disponible' => true,
                'disponible_hoy' => true,
            ],
            [
                'nombre' => 'MANEJO DE MATERIALES DEL KIT DE LABORATORIO DE FÍSICA (MECANICA I/PARTE II)',
                'tipo' => 'T',
                'descripcion' => 'Taller sobre manejo de materiales de laboratorio de física parte II.',
                'categoria' => 'Taller',
                'duracion' => 10,
                'disponible' => true,
                'disponible_hoy' => true,
            ],
            [
                'nombre' => 'ESTRATEGIAS DIDÁCTICAS PARA LA INNOVACIÓN EN LA ENSEÑANZA Y APRENDIZAJE DE LA QUÍMICA',
                'tipo' => 'T',
                'descripcion' => 'Estrategias innovadoras para la enseñanza de química.',
                'categoria' => 'Taller',
                'duracion' => 10,
                'disponible' => true,
                'disponible_hoy' => true,
            ],
            [
                'nombre' => 'MANEJO DE MATERIALES DEL KIT DE LABORATORIO DE QUÍMICA',
                'tipo' => 'T',
                'descripcion' => 'Taller práctico sobre materiales de laboratorio de química.',
                'categoria' => 'Taller',
                'duracion' => 10,
                'disponible' => true,
                'disponible_hoy' => true,
            ],
            [
                'nombre' => 'El mundo entre la quimica, el arte y los vegetales',
                'tipo' => 'T',
                'descripcion' => 'Taller interdisciplinario sobre química, arte y botánica.',
                'categoria' => 'Taller',
                'duracion' => 10,
                'disponible' => true,
                'disponible_hoy' => true,
            ],
            [
                'nombre' => 'LA QUIMÍCA EN LO COTIDIANO Y LAS DANZAS TRADICIONALES',
                'tipo' => 'T',
                'descripcion' => 'Taller sobre química aplicada a la vida cotidiana y danzas.',
                'categoria' => 'Taller',
                'duracion' => 10,
                'disponible' => true,
                'disponible_hoy' => true,
            ],
            [
                'nombre' => 'TALLER CONOCIENDO EL APASIONANTE MUNDO DE LA QUÍMICA',
                'tipo' => 'T',
                'descripcion' => 'Taller introductorio al mundo de la química.',
                'categoria' => 'Taller',
                'duracion' => 10,
                'disponible' => true,
                'disponible_hoy' => true,
            ],
            [
                'nombre' => 'ESTRATEGIAS DIDÁCTICAS PARA LA INNOVACIÓN EN LA ENSEÑANZA Y EL APRENDIZAJE DE LA MATEMÁTICA',
                'tipo' => 'T',
                'descripcion' => 'Estrategias innovadoras para la enseñanza de matemática.',
                'categoria' => 'Taller',
                'duracion' => 10,
                'disponible' => true,
                'disponible_hoy' => true,
            ],
            [
                'nombre' => 'FRACCIONES DE MATEMATICA',
                'tipo' => 'T',
                'descripcion' => 'Taller sobre enseñanza de fracciones matemáticas.',
                'categoria' => 'Taller',
                'duracion' => 10,
                'disponible' => true,
                'disponible_hoy' => true,
            ],
            [
                'nombre' => 'ESTRATEGIAS DIDÁCTICAS PARA LA INNOVACIÓN EN LA ENSEÑANZA Y EL APRENDIZAJE DE LA MATEMÁTICA. Jornada II',
                'tipo' => 'T',
                'descripcion' => 'Segunda parte del taller de estrategias para matemática.',
                'categoria' => 'Taller',
                'duracion' => 10,
                'disponible' => true,
                'disponible_hoy' => true,
            ],
            [
                'nombre' => 'CONSTRUCCIÓN Y USO DIDÁCTICO DEL TANGRAM',
                'tipo' => 'T',
                'descripcion' => 'Taller sobre construcción y uso educativo del tangram.',
                'categoria' => 'Taller',
                'duracion' => 10,
                'disponible' => true,
                'disponible_hoy' => true,
            ],
            [
                'nombre' => 'JUEGOS Y ALGO MÁS',
                'tipo' => 'T',
                'descripcion' => 'Taller sobre juegos educativos.',
                'categoria' => 'Taller',
                'duracion' => 10,
                'disponible' => true,
                'disponible_hoy' => true,
            ],
            [
                'nombre' => 'MATEMÁTICA Y ARTES',
                'tipo' => 'T',
                'descripcion' => 'Taller interdisciplinario entre matemática y artes.',
                'categoria' => 'Taller',
                'duracion' => 10,
                'disponible' => true,
                'disponible_hoy' => true,
            ],
            [
                'nombre' => 'TALLER LAS MEDIDAS DEL MUNDO',
                'tipo' => 'T',
                'descripcion' => 'Taller sobre sistemas de medida.',
                'categoria' => 'Taller',
                'duracion' => 10,
                'disponible' => true,
                'disponible_hoy' => true,
            ],
            [
                'nombre' => 'DISEÑO DE TAREAS COMPLEMENTARIAS DE MATEMÁTICA',
                'tipo' => 'T',
                'descripcion' => 'Taller sobre diseño de tareas complementarias en matemática.',
                'categoria' => 'Taller',
                'duracion' => 10,
                'disponible' => true,
                'disponible_hoy' => true,
            ],
            [
                'nombre' => 'TALLER PARA EL DISEÑO DE ACTIVIDADES REMEDIALES DE MATEMÁTICA',
                'tipo' => 'T',
                'descripcion' => 'Taller sobre diseño de actividades remediales en matemática.',
                'categoria' => 'Taller',
                'duracion' => 10,
                'disponible' => true,
                'disponible_hoy' => true,
            ],
            [
                'nombre' => 'MATEMATICA RECREATIVA',
                'tipo' => 'T',
                'descripcion' => 'Taller de matemática aplicada de forma recreativa.',
                'categoria' => 'Taller',
                'duracion' => 10,
                'disponible' => true,
                'disponible_hoy' => true,
            ],
            [
                'nombre' => 'TALLER BUSCANDO LAS MATEMÁTICAS',
                'tipo' => 'T',
                'descripcion' => 'Taller sobre identificación de conceptos matemáticos en la vida cotidiana.',
                'categoria' => 'Taller',
                'duracion' => 10,
                'disponible' => true,
                'disponible_hoy' => true,
            ],
            [
                'nombre' => 'Por amor a las matemáticas',
                'tipo' => 'T',
                'descripcion' => 'Taller motivacional sobre matemáticas.',
                'categoria' => 'Taller',
                'duracion' => 10,
                'disponible' => true,
                'disponible_hoy' => true,
            ],
            [
                'nombre' => 'Acertijos Divertidos',
                'tipo' => 'T',
                'descripcion' => 'Taller de acertijos matemáticos.',
                'categoria' => 'Taller',
                'duracion' => 10,
                'disponible' => true,
                'disponible_hoy' => true,
            ],
            [
                'nombre' => 'MUÑECAS INTERACTIVAS',
                'tipo' => 'T',
                'descripcion' => 'Taller sobre creación de muñecas interactivas con fines educativos.',
                'categoria' => 'Taller',
                'duracion' => 10,
                'disponible' => true,
                'disponible_hoy' => true,
            ],
            [
                'nombre' => 'TALLER DE TEATRO ACCION CREATIVA',
                'tipo' => 'T',
                'descripcion' => 'Taller de teatro creativo.',
                'categoria' => 'Taller',
                'duracion' => 10,
                'disponible' => true,
                'disponible_hoy' => true,
            ],
            [
                'nombre' => 'TALLER DE TEATRO LA EXPRESIÓN DRAMÁTICA',
                'tipo' => 'T',
                'descripcion' => 'Taller sobre expresión dramática.',
                'categoria' => 'Taller',
                'duracion' => 10,
                'disponible' => true,
                'disponible_hoy' => true,
            ],
            [
                'nombre' => 'TALLER JOROPO ORIENTAL, SAN JUAN DE BARLOVENTO, CULO ´E PUYA, MINA',
                'tipo' => 'T',
                'descripcion' => 'Taller sobre danzas tradicionales venezolanas.',
                'categoria' => 'Taller',
                'duracion' => 10,
                'disponible' => true,
                'disponible_hoy' => true,
            ],
            [
                'nombre' => 'TALLER GAITA DE TAMBORA, TAMBOR CORIANO, SANGUEO Y GOLPE DE SAN MILLAN',
                'tipo' => 'T',
                'descripcion' => 'Taller sobre ritmos musicales tradicionales.',
                'categoria' => 'Taller',
                'duracion' => 10,
                'disponible' => true,
                'disponible_hoy' => true,
            ],
            [
                'nombre' => 'TALLER LÚDICO DE FRANCÉS',
                'tipo' => 'T',
                'descripcion' => 'Taller de francés a través del juego.',
                'categoria' => 'Taller',
                'duracion' => 10,
                'disponible' => true,
                'disponible_hoy' => true,
            ],
            [
                'nombre' => 'TALLER LA MARAVILLA DEL INGLES EN NUESTRAS VACACIONES',
                'tipo' => 'T',
                'descripcion' => 'Taller de inglés para vacaciones.',
                'categoria' => 'Taller',
                'duracion' => 10,
                'disponible' => true,
                'disponible_hoy' => true,
            ],
            [
                'nombre' => 'Aprendiendo inglés y francés en vacaciones',
                'tipo' => 'T',
                'descripcion' => 'Taller combinado de inglés y francés para vacaciones.',
                'categoria' => 'Taller',
                'duracion' => 10,
                'disponible' => true,
                'disponible_hoy' => true,
            ],
            [
                'nombre' => 'TALLER INGLÉS PARA PRINCIPIANTES',
                'tipo' => 'T',
                'descripcion' => 'Taller introductorio de inglés.',
                'categoria' => 'Taller',
                'duracion' => 10,
                'disponible' => true,
                'disponible_hoy' => true,
            ],
            [
                'nombre' => 'FORMACIÓN EN MECATRONICA PARA PROFESORES',
                'tipo' => 'T',
                'descripcion' => 'Taller de mecatrónica para docentes.',
                'categoria' => 'Taller',
                'duracion' => 10,
                'disponible' => true,
                'disponible_hoy' => true,
            ],
            [
                'nombre' => 'IMPRESIÓN 3D',
                'tipo' => 'T',
                'descripcion' => 'Taller sobre impresión 3D.',
                'categoria' => 'Taller',
                'duracion' => 10,
                'disponible' => true,
                'disponible_hoy' => true,
            ],
            [
                'nombre' => 'ARDUINO NIVEL 1',
                'tipo' => 'T',
                'descripcion' => 'Taller introductorio de Arduino.',
                'categoria' => 'Taller',
                'duracion' => 10,
                'disponible' => true,
                'disponible_hoy' => true,
            ],
            [
                'nombre' => 'PYTHON',
                'tipo' => 'T',
                'descripcion' => 'Taller de programación en Python.',
                'categoria' => 'Taller',
                'duracion' => 10,
                'disponible' => true,
                'disponible_hoy' => true,
            ],
            [
                'nombre' => 'FORMACIÓN DE PROGRAMAS OFIMÁTICOS. WORD BÁSICO',
                'tipo' => 'T',
                'descripcion' => 'Taller básico de Microsoft Word.',
                'categoria' => 'Taller',
                'duracion' => 10,
                'disponible' => true,
                'disponible_hoy' => true,
            ],
            [
                'nombre' => 'TALLER EL MUNDO DEL TIK TOK',
                'tipo' => 'T',
                'descripcion' => 'Taller sobre creación de contenido en TikTok.',
                'categoria' => 'Taller',
                'duracion' => 10,
                'disponible' => true,
                'disponible_hoy' => true,
            ],
            [
                'nombre' => 'LA RADIO COMO MEDIO DE COMUNICACIÓN',
                'tipo' => 'T',
                'descripcion' => 'Taller sobre producción radiofónica.',
                'categoria' => 'Taller',
                'duracion' => 10,
                'disponible' => true,
                'disponible_hoy' => true,
            ],
            [
                'nombre' => 'FORMACIÓN DE ROBÓTICA EDUCATIVA REGRESO A CLASES 2024/2025',
                'tipo' => 'T',
                'descripcion' => 'Taller de robótica educativa.',
                'categoria' => 'Taller',
                'duracion' => 10,
                'disponible' => true,
                'disponible_hoy' => true,
            ],
            [
                'nombre' => 'PROGRAMACIÓN APLICADA A ROBOT SEGUIDOR DE LÍNEAS',
                'tipo' => 'T',
                'descripcion' => 'Taller sobre programación de robots seguidores de línea.',
                'categoria' => 'Taller',
                'duracion' => 10,
                'disponible' => true,
                'disponible_hoy' => true,
            ],
            [
                'nombre' => 'MECATRÓNICA Y PROGRAMACIÓN APLICADA A PROYECTOS EDUCATIVOS',
                'tipo' => 'T',
                'descripcion' => 'Taller sobre mecatrónica aplicada a proyectos educativos.',
                'categoria' => 'Taller',
                'duracion' => 10,
                'disponible' => true,
                'disponible_hoy' => true,
            ],
            [
                'nombre' => 'IOT INTERNET DE LAS COSAS',
                'tipo' => 'T',
                'descripcion' => 'Taller sobre Internet de las Cosas.',
                'categoria' => 'Taller',
                'duracion' => 10,
                'disponible' => true,
                'disponible_hoy' => true,
            ],
            [
                'nombre' => 'CONVERSATORIO Jornada reflexiva sobre el cambio climático. Un problema que nos afecta a todos',
                'tipo' => 'T',
                'descripcion' => 'Conversatorio sobre cambio climático.',
                'categoria' => 'Taller',
                'duracion' => 10,
                'disponible' => true,
                'disponible_hoy' => true,
            ],
            [
                'nombre' => 'TALLER PROCESO DE ELABORACIÓN DE ITEM. LA VALIDEZ Y CONFIABILIDAD DEL ITEM',
                'tipo' => 'T',
                'descripcion' => 'Taller sobre elaboración de ítems de evaluación.',
                'categoria' => 'Taller',
                'duracion' => 10,
                'disponible' => true,
                'disponible_hoy' => true,
            ],
            [
                'nombre' => 'Ajedrez',
                'tipo' => 'T',
                'descripcion' => 'Taller básico de ajedrez.',
                'categoria' => 'Taller',
                'duracion' => 10,
                'disponible' => true,
                'disponible_hoy' => true,
            ],
            [
                'nombre' => 'TALLER AJEDREZ INTERMEDIO PARA NIÑOS',
                'tipo' => 'T',
                'descripcion' => 'Taller de ajedrez nivel intermedio para niños.',
                'categoria' => 'Taller',
                'duracion' => 10,
                'disponible' => true,
                'disponible_hoy' => true,
            ],
            [
                'nombre' => 'TALLER CUÉNTAME UN CUENTO',
                'tipo' => 'T',
                'descripcion' => 'Taller sobre narración de cuentos.',
                'categoria' => 'Taller',
                'duracion' => 10,
                'disponible' => true,
                'disponible_hoy' => true,
            ],
            [
                'nombre' => 'TALLER MATERIALES ARTESANALES PARA EL APRENDIZAJE COMPUTACIONAL',
                'tipo' => 'T',
                'descripcion' => 'Taller sobre creación de materiales didácticos para computación.',
                'categoria' => 'Taller',
                'duracion' => 10,
                'disponible' => true,
                'disponible_hoy' => true,
            ],
            [
                'nombre' => 'INDUCCIÓN AL PROGRAMA EIS',
                'tipo' => 'T',
                'descripcion' => 'Taller de inducción al programa EIS.',
                'categoria' => 'Taller',
                'duracion' => 10,
                'disponible' => true,
                'disponible_hoy' => true,
            ],
            [
                'nombre' => 'INTRODUCCION DE HABILIDADES SOCIOEMOCIONALES PARA LOS DOCENTES',
                'tipo' => 'T',
                'descripcion' => 'Taller sobre habilidades socioemocionales para docentes.',
                'categoria' => 'Taller',
                'duracion' => 10,
                'disponible' => true,
                'disponible_hoy' => true,
            ],

            // Cursos
            [
                'nombre' => 'MATEMÁTICA Y BOTÁNICA. BOTÁNICA POR UN DÍA',
                'tipo' => 'C',
                'descripcion' => 'Curso interdisciplinario entre matemática y botánica.',
                'categoria' => 'Curso',
                'duracion' => 30,
                'disponible' => true,
                'disponible_hoy' => true,
            ],
            [
                'nombre' => 'RESOLUCIÓN DE PROBLEMAS',
                'tipo' => 'C',
                'descripcion' => 'Curso sobre estrategias de resolución de problemas.',
                'categoria' => 'Curso',
                'duracion' => 30,
                'disponible' => true,
                'disponible_hoy' => true,
            ],
            [
                'nombre' => 'LAS MEDIDAS DEL MUNDO',
                'tipo' => 'C',
                'descripcion' => 'Curso sobre sistemas de medida.',
                'categoria' => 'Curso',
                'duracion' => 30,
                'disponible' => true,
                'disponible_hoy' => true,
            ],
            [
                'nombre' => 'ESCRITURA CREATIVA EN ESCENA',
                'tipo' => 'C',
                'descripcion' => 'Curso de escritura creativa aplicada al teatro.',
                'categoria' => 'Curso',
                'duracion' => 30,
                'disponible' => true,
                'disponible_hoy' => true,
            ],
            [
                'nombre' => 'CURSO BÁSICO DE INGLÉS PARA PRINCIPIANTES Nivel 1',
                'tipo' => 'C',
                'descripcion' => 'Curso básico de inglés nivel 1.',
                'categoria' => 'Curso',
                'duracion' => 30,
                'disponible' => true,
                'disponible_hoy' => true,
            ],
            [
                'nombre' => 'CURSO BÁSICO DE INGLÉS PARA PRINCIPIANTES Nivel 2',
                'tipo' => 'C',
                'descripcion' => 'Curso básico de inglés nivel 2.',
                'categoria' => 'Curso',
                'duracion' => 30,
                'disponible' => true,
                'disponible_hoy' => true,
            ],
            [
                'nombre' => 'MECATRÓNICA CREATIVA',
                'tipo' => 'C',
                'descripcion' => 'Curso de mecatrónica con enfoque creativo.',
                'categoria' => 'Curso',
                'duracion' => 30,
                'disponible' => true,
                'disponible_hoy' => true,
            ],
            [
                'nombre' => 'MECATRÓNICA INTERMEDIA',
                'tipo' => 'C',
                'descripcion' => 'Curso intermedio de mecatrónica.',
                'categoria' => 'Curso',
                'duracion' => 30,
                'disponible' => true,
                'disponible_hoy' => true,
            ],
            [
                'nombre' => 'USO INTELIGENTE DE LAS REDES SOCIALES',
                'tipo' => 'C',
                'descripcion' => 'Curso sobre uso responsable de redes sociales.',
                'categoria' => 'Curso',
                'duracion' => 30,
                'disponible' => true,
                'disponible_hoy' => true,
            ],
            [
                'nombre' => 'CURSO PASANTIA PARA DOCENTES DE EDUCACIÓN BÁSICA EN EL USO INTELIGENTE DE LAS TIC EN LA ERA DE LA INTELIGENCIA ARTIFICIAL',
                'tipo' => 'C',
                'descripcion' => 'Curso sobre TIC e inteligencia artificial para docentes.',
                'categoria' => 'Curso',
                'duracion' => 30,
                'disponible' => true,
                'disponible_hoy' => true,
            ],
            [
                'nombre' => 'Introducción a la Informática',
                'tipo' => 'C',
                'descripcion' => 'Curso introductorio a la informática.',
                'categoria' => 'Curso',
                'duracion' => 30,
                'disponible' => true,
                'disponible_hoy' => true,
            ],
            [
                'nombre' => 'INTELIGENCIA ARTIFICIAL - FUNDAMENTOS DE MACHINE LEARNING Y PROBLEMAS DE REGRESIÓN',
                'tipo' => 'C',
                'descripcion' => 'Curso sobre fundamentos de inteligencia artificial.',
                'categoria' => 'Curso',
                'duracion' => 30,
                'disponible' => true,
                'disponible_hoy' => true,
            ],
            [
                'nombre' => 'INDICADORES DE CALIDAD DE VIDA ESTUDIANTIL PARA LA EVALUACIÓN DE LA CALIDAD EDUCATIVA',
                'tipo' => 'C',
                'descripcion' => 'Curso sobre indicadores de calidad educativa.',
                'categoria' => 'Curso',
                'duracion' => 30,
                'disponible' => true,
                'disponible_hoy' => true,
            ],
            [
                'nombre' => 'ESTRATEGIA Y TÁCTICA DEL JUEGO DE AJEDREZ',
                'tipo' => 'C',
                'descripcion' => 'Curso avanzado de estrategias de ajedrez.',
                'categoria' => 'Curso',
                'duracion' => 30,
                'disponible' => true,
                'disponible_hoy' => true,
            ],
            [
                'nombre' => 'AJEDREZ MULTINIVEL',
                'tipo' => 'C',
                'descripcion' => 'Curso de ajedrez para diferentes niveles.',
                'categoria' => 'Curso',
                'duracion' => 30,
                'disponible' => true,
                'disponible_hoy' => true,
            ],
            [
                'nombre' => 'ORGANIZACIÓN DE GRUPOS ESTABLES PARA LA TRANSFORMACIÓN CURRICULAR POR LA CALIDAD EDUCATIVA CON EL USO DE LAS TICS',
                'tipo' => 'C',
                'descripcion' => 'Curso sobre organización de grupos con TIC.',
                'categoria' => 'Curso',
                'duracion' => 30,
                'disponible' => true,
                'disponible_hoy' => true,
            ],
            [
                'nombre' => 'PENSAMIENTO COMPUTACIONAL Y CALIDAD EDUCATIVA',
                'tipo' => 'C',
                'descripcion' => 'Curso sobre pensamiento computacional en educación.',
                'categoria' => 'Curso',
                'duracion' => 30,
                'disponible' => true,
                'disponible_hoy' => true,
            ],
            [
                'nombre' => 'DEFENSA PERSONAL',
                'tipo' => 'C',
                'descripcion' => 'Curso de técnicas básicas de defensa personal.',
                'categoria' => 'Curso',
                'duracion' => 30,
                'disponible' => true,
                'disponible_hoy' => true,
            ],

            // Diplomados
            [
                'nombre' => 'DIPLOMADO INVESTIGACIÓN SOCIOCRÍTICA EN CIENCIAS NATURALES, MATEMÁTICA O TECNOLOGÍA',
                'tipo' => 'D',
                'descripcion' => 'Diplomado sobre investigación en ciencias.',
                'categoria' => 'Diplomado',
                'duracion' => 60,
                'disponible' => true,
                'disponible_hoy' => true,
            ],
        ];

        foreach ($formaciones as $formacion) {
            DB::table('formaciones')->insert($formacion);
        }
    }
}